version: "3.3"
services:
  web:
    build: ./app
    ports:
      - "5000:5000"
    volumes:
      - ./app/:/app/
    depends_on:
      - db
  db:
    image: postgres:10
    env_file: .env
    expose:
      - 5432
